// <auto-generated />
namespace Commerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CommerceModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommerceModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201405201512149_CommerceModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
